name: football_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  badges: ^3.1.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  toast: ^0.3.0
  path_provider: ^2.1.2
  flutter_colorpicker: ^1.0.3
  provider: 6.1.1
  shared_preferences: ^2.2.2
  bugsnag_flutter: ^3.0.2
  get: ^4.6.6
  meta: ^1.11.0
  fancy_password_field: ^2.0.6
  http: ^1.2.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  intl: ^0.19.0
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  iconsax_flutter: ^1.0.0
  meta_seo: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
    - web/Robots.txt
    - web/sitemap.xml


  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: google_fonts/PlusJakartaSans-Regular.ttf
        - asset: google_fonts/PlusJakartaSans-SemiBold.ttf
          weight: 700
        - asset: google_fonts/PlusJakartaSans-SemiBold.ttf
          weight: 500
